### ISSUE TITLE
install instructions do not install everything needed for gocode to function properly

### ISSUE THREAD

**Issue by wobbol** [mrobinsn/go-rtorrent#11]
To be clear, I can import this package and build just fine after a `go get github.com/mrobinsn/go-rtorrent`

[gocode](https://github.com/mdempsky/gocode) cant see what the return type of `rtorrent.New()` is after just a `go get github.com/mrobinsn/go-rtorrent`

after some mucking about running this `go install -i github.com/mrobinsn/go-rtorrent` set everything straight. Note the `-i`. I don't know why this works.

Not sure how to fix this, it seems like the instructions from the readme should work.
If you want some debugging info or a patch or something I think I can spare some time.

**Comment by wobbol** [comment]
before I forget, here is the suggested solution from gocode. I'm a bit too tired to understand it atm.
mdempsky/gocode#102

**Comment by mrobinsn** [comment]
That is strange, since `go get` [should ](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies)be doing the install for you. Are you using modules?

**Comment by wobbol** [comment]
no, I'm not using modules. This is what my code looks like.
```
package main

import (
	"fmt"
	"github.com/mrobinsn/go-rtorrent/rtorrent"
	"log"
)

func main() {
	rtConn := rtorrent.New("http://example.com/RPC2", false)

	list, err := rtConn.GetTorrents(rtorrent.ViewMain)
	if err != nil {
		log.Fatalln(err)
	}

	for _, torrent := range list {
		fmt.Println(torrent.Pretty())
	}
}
```
IIRC, `rtorrent.*` functions were all seen by gocode, but `rtConn.*` functions weren't being resolved.

I haven't tried to reproduce the issue.

**Comment by mrobinsn** [comment]
I'm inclined to say this was/is an issue with `gocode`. If you haven't already, look into `gopls` as it will eventually replace `gocode` (I've been using it exclusively for a couple months now).
