### ISSUE TITLE
date attributes?

### ISSUE THREAD

**Issue by justinrush** [mrobinsn/go-rtorrent#16]
It doesn't seem possible to get any date related attributes from the torrents - like date added, completed, created, etc. Am I missing something?

If not, I'd be open to looking at the xmlrpc spec and creating a PR if you are open to PRs.  Of course, if you just want to do it, i'm open to that too :)

**Comment by mrobinsn** [comment]
You're correct that those fields aren't currently supported.

I'm not sure I will have time soon to add this but I'd be happy to take a look at PR if you want to dig in..

Looking at the [rtorrent reference](https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-(WIP)), I think you'd want to pass through: `d.creation_date`, `d.timestamp.finished`, and `d.timestamp.started`. Docs aren't clear on what the time/date format is, so you'll probably have to play around a little to figure that out and get it converted to a go `time.Time`.

**Comment by justinrush** [comment]
added PR, however, tests are failing. It looks like the test torrent is no longer active

**Comment by mrobinsn** [comment]
Thanks for the contribution! Released in `v1.6.0`: https://github.com/mrobinsn/go-rtorrent/releases/tag/v1.6.0
