### ISSUE TITLE
add torrent from file?

### ISSUE THREAD

**Issue by justinrush** [mrobinsn/go-rtorrent#18]
Trying to add a torrent from a link generated by Jackett and realized with a face palm that it isn't working because I'm sending an internal URL to a rtorrent server that can't reach said URL. Is there a good way to just send the binary torrent file data to the rtorrent server rather than passing it a URL?

**Comment by mrobinsn** [comment]
Hey Justin, try the `AddTorrent(data []byte)` function, it should handle that case perfectly.

**Comment by justinrush** [comment]
not sure how i missed that function existing, thanks for pointing out what my eyes failed to see!
