### ISSUE TITLE
No type checking is performed

### ISSUE THREAD

**Issue by schoentoon** [mrobinsn/go-rtorrent#2]
It seems like no type checking is performed when casting the outputs of calls like `IP()` `Name()` `DownTotal()` `UpTotal()` etc..

```panic: interface conversion: interface {} is []interface {}, not int

goroutine 1 [running]:
github.com/tehjojo/go-rtorrent/rtorrent.(*RTorrent).DownTotal(0xc42000e038, 0xc42000e038, 0x4, 0xc400000008)
        /go/src/github.com/tehjojo/go-rtorrent/rtorrent/rtorrent.go:98 +0xb8```

**Comment by mrobinsn** [comment]
Made some improvements to the error handling that should prevent this error most of the time. Still need to add proper type checking. Planning to add some tests to this repo soon.
